<?php
if(session_status()===PHP_SESSION_NONE)session_start(); require_once "DBconnect.php";
$raw=$_SESSION['customer_id']??$_SESSION['Customer_ID']??$_SESSION['Customer_id']??$_SESSION['user_id']??null;
$customer_id=(int)preg_replace('/[^0-9]/','',(string)$raw); if($customer_id<=0){header("Location: login.php");exit;}
$q="SELECT o.*,p.Plant_name,e.exchange_id,e.status AS exchange_status,e.Exchange_value FROM orders o LEFT JOIN plant p ON p.Plant_ID=o.Plant_id LEFT JOIN exchange e ON e.Order_ID=o.Order_id WHERE o.Customer_id=? ORDER BY o.Order_id DESC,e.exchange_id DESC";
$s=mysqli_prepare($conn,$q);mysqli_stmt_bind_param($s,"i",$customer_id);mysqli_stmt_execute($s);$result=mysqli_stmt_get_result($s);
?>
<!doctype html><html><head><meta charset="utf-8"><title>My Orders - Plant Hub</title><style>
body{font-family:Segoe UI,sans-serif;background:#eef7f2;margin:0;color:#1e293b}.container{max-width:1200px;margin:30px auto;padding:0 20px}.card{background:#fff;padding:25px;border-radius:14px}.orders{width:100%;border-collapse:collapse}.orders th,.orders td{padding:12px;border-bottom:1px solid #e2e8f0;text-align:left}.orders th{background:#f8fafc}.b{display:inline-block;padding:7px 10px;border-radius:7px;font-size:12px;font-weight:700}.none{background:#f1f5f9}.pending{background:#fef3c7;color:#92400e}.approved{background:#dbeafe;color:#1d4ed8}.completed{background:#dcfce7;color:#166534}.btn{background:#0284c7;color:white;text-decoration:none;padding:8px 11px;border-radius:7px;font-weight:700;font-size:12px}.disabled{background:#e2e8f0;color:#64748b;padding:8px 11px;border-radius:7px;font-size:12px;font-weight:700}</style></head><body>
<?php if(file_exists("header.php"))include"header.php";?><div class="container"><div class="card"><h2>My Orders 📦</h2><p>Purchase history and plant exchange.</p><table class="orders"><tr><th>Order #</th><th>Plant</th><th>Amount</th><th>Points</th><th>Exchange Status</th><th>Exchange</th></tr>
<?php $seen=[];while($r=mysqli_fetch_assoc($result)): $oid=(int)$r["Order_id"];if(isset($seen[$oid]))continue;$seen[$oid]=1;$st=strtolower(trim((string)($r["exchange_status"]??"")));$st=$st?:'none';?>
<tr><td>#<?=$oid?></td><td>🌱 <?=htmlspecialchars($r["Plant_name"]??"Unknown Plant")?></td><td>৳<?=number_format((float)$r["Amount"],2)?></td><td><?=((int)($r["points_redeemed"]??0))?> PTS</td><td>
<?php if($st==='pending'):?><span class="b pending">⏳ Exchange Pending</span><?php elseif($st==='approved'):?><span class="b approved">✓ Exchange Approved</span><?php elseif($st==='completed'):?><span class="b completed">✓ Exchange Completed</span><?php else:?><span class="b none">No Exchange</span><?php endif;?></td><td>
<?php if($st==='approved'):?><a class="btn" href="process_exchanges.php?action=complete&exchange_id=<?=(int)$r["exchange_id"]?>" onclick="return confirm('Complete this approved exchange?')">🔄 Complete Exchange</a>
<?php elseif($st==='pending'):?><span class="disabled">⏳ Waiting for Employee</span><?php elseif($st==='completed'):?><span class="disabled">✓ Done</span><?php else:?><a class="btn" href="process_exchanges.php?order_id=<?=$oid?>&offered_plant_id=<?=(int)$r["Plant_id"]?>">🔄 Request Exchange</a><?php endif;?></td></tr>
<?php endwhile;?></table></div></div></body></html>